# Generated by Django 4.2.4 on 2023-10-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('dob', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_FoodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('doner_id', models.IntegerField(default='', max_length=100)),
                ('receiver_id', models.IntegerField(default='', max_length=100)),
                ('food_name', models.CharField(default='', max_length=100)),
                ('expire', models.DateField(default='', max_length=100)),
                ('quantity', models.PositiveIntegerField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('doner_id', models.IntegerField(default='', max_length=100)),
                ('receiver_id', models.IntegerField(default='', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_MedicineDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doner_id', models.IntegerField(default='', max_length=100)),
                ('receiver_id', models.IntegerField(default='', max_length=100)),
                ('medicine_name', models.CharField(default='', max_length=100)),
                ('quantity', models.PositiveIntegerField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('dob', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=128)),
                ('phone', models.CharField(default='', max_length=15)),
                ('id_card', models.CharField(default='', max_length=20)),
                ('img', models.ImageField(upload_to='user_images/')),
                ('account_detail', models.CharField(default='', max_length=100)),
                ('current_status', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
