# Generated by Django 4.2.4 on 2023-11-01 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0004_remove_tbl_fooddonation_doner_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('quantity', models.IntegerField(default='', max_length=100)),
                ('expire', models.CharField(default='', max_length=100)),
                ('donor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charityapp.tbl_donor')),
            ],
        ),
        migrations.RemoveField(
            model_name='tbl_fooddonation',
            name='food_name',
        ),
        migrations.DeleteModel(
            name='tbl_MedicineDonation',
        ),
    ]
