# Generated by Django 4.2.4 on 2023-11-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0005_tbl_medicine_remove_tbl_fooddonation_food_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_fooddonation',
            name='otherfoodname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
