# Generated by Django 4.2.4 on 2023-11-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0007_remove_tbl_fooddonation_otherfoodname'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_donor',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tbl_receiver',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
