# Generated by Django 4.2.4 on 2023-11-03 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0008_tbl_donor_status_tbl_receiver_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_admin',
            old_name='name',
            new_name='email',
        ),
    ]
