# Generated by Django 4.2.4 on 2023-11-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0009_rename_name_tbl_admin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_donor',
            name='utype',
            field=models.CharField(default='', max_length=100),
        ),
    ]
