# Generated by Django 4.2.4 on 2023-11-03 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0010_tbl_donor_utype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_admin',
        ),
    ]
