# Generated by Django 4.2.4 on 2023-11-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0012_tbl_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_fooddonation',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tbl_medicine',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
