# Generated by Django 4.2.4 on 2023-11-07 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0013_tbl_fooddonation_status_tbl_medicine_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_buyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default='', max_length=100)),
                ('food_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charityapp.tbl_fooddonation')),
                ('receiver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charityapp.tbl_receiver')),
            ],
        ),
    ]
