# Generated by Django 4.2.4 on 2023-11-08 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0014_tbl_buyproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_buyproduct',
            name='fund_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charityapp.tbl_funding'),
        ),
        migrations.AddField(
            model_name='tbl_buyproduct',
            name='medicine_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charityapp.tbl_medicine'),
        ),
    ]
