# Generated by Django 4.2.4 on 2023-11-08 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0015_tbl_buyproduct_fund_id_tbl_buyproduct_medicine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_buyproduct',
            name='donor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charityapp.tbl_donor'),
        ),
    ]
