# Generated by Django 4.2.4 on 2023-11-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0017_tbl_deliverer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_deliverer',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
