# Generated by Django 4.2.4 on 2023-11-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0019_tbl_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_fooddonation',
            name='fd_status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tbl_funding',
            name='fund_status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tbl_medicine',
            name='med_status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
