# Generated by Django 4.1.4 on 2024-02-29 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0020_tbl_fooddonation_fd_status_tbl_funding_fund_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charityapp.tbl_deliverer')),
                ('receiver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charityapp.tbl_receiver')),
            ],
        ),
    ]
