# Generated by Django 4.1.4 on 2024-02-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0021_deliverrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverrequest',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
