# Generated by Django 4.1.4 on 2024-02-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0022_deliverrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_deliverer',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
