# Generated by Django 5.0.2 on 2024-03-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0023_tbl_deliverer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_buyproduct',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
