# Generated by Django 4.1.4 on 2024-03-12 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0024_tbl_buyproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_deliverer',
            name='receiver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charityapp.tbl_receiver'),
        ),
    ]
